### ISSUE TITLE
NT QQ 消息数据解码

### ISSUE THREAD

**Issue by Mythologyli** [QQBackup/qq-win-db-key#13]
感谢各位作者！

参考仓库教程，现在已经成功解密了 nt_msg.db。但是聊天记录是用二进制储存的，我只发现里面的文本应该是 UTF-8。试了一下之前的项目，好像不能正常工作，也许腾讯改格式了。各位大佬有什么想法吗？

**Comment by Young-Lord** [comment]
https://github.com/QQBackup/QQ-History-Backup/issues/9#issuecomment-1740537724

hook这些东西，根据stacktrace找到编码/解码部分（盲猜protobuf）试试

**Comment by Mythologyli** [comment]
感谢！确实是 protobuf。目前写了两个清图片/文件的 py 脚本：

https://github.com/Mythologyli/qq-nt-db

**Comment by Young-Lord** [comment]
好！丢个pr？

**Comment by Young-Lord** [comment]
顺带一提，导出未加密数据库可以参考一下[Android的](https://github.com/QQBackup/qq-win-db-key/blob/master/android_dump.js)

**Comment by Mythologyli** [comment]
> 顺带一提，导出未加密数据库可以参考一下[Android的](https://github.com/QQBackup/qq-win-db-key/blob/master/android_dump.js) `ATTACH DATABASE /sdcard/Download/export.db AS plaintext KEY '';SELECT sqlcipher_export('plaintext');DETACH DATABASE plaintext;`

我现在是在命令行下用 sqlcipher 这样解密的，不过好几个数据库会报错，只能 dump 出 sql 再重建。不知道如果直接 hook 后执行会怎么样

**Comment by Young-Lord** [comment]
Duplicate of https://github.com/QQBackup/QQ-History-Backup/issues/9
