### ISSUE TITLE
获取之后如何获得对应消息的 消息 id

### ISSUE THREAD

**Issue by shenjackyuanjie** [QQBackup/qq-win-db-key#18]
目前拆包完成之后
我用
https://github.com/saucer-man/qq_msg_decode
这玩意 decode了
但是没有那个 id 项

![image](https://github.com/QQBackup/qq-win-db-key/assets/54507071/f0009cd2-1113-4f23-b472-2fda5ca7b8d9)

类似 icalingua 数据库里的 _id 项

![image](https://github.com/QQBackup/qq-win-db-key/assets/54507071/43fad2ea-8605-4663-b7cd-8a99c585d520)

**Comment by shenjackyuanjie** [comment]
![image](https://github.com/QQBackup/qq-win-db-key/assets/54507071/afe7d617-3024-4968-a2e9-17e5597971be)

大概观察了一下实际的 id
我的感觉是 Time-Rand-SenderUin 三个字段通过转换拼起来的

**Comment by shenjackyuanjie** [comment]
![image](https://github.com/QQBackup/qq-win-db-key/assets/54507071/73a60dbe-43a3-4250-baf9-d08292de6e65)

 我感觉目测有关系，但不知道是啥.png

**Comment by Young-Lord** [comment]
搜一下就有了，本地生成的。
https://github.com/Icalingua-plus-plus/Icalingua-plus-plus/blob/067b7619b8b1dbbd66d953e0ffa43377b32f5f43/icalingua-bridge-oicq/adapters/oicqAdapter.ts#L129
https://github.com/Icalingua-plus-plus/oicq-icalingua-plus-plus/blob/37b729b6ead8b0b9c166cca98ead240034c8a25f/lib/message/parser.js#L665

**Comment by Young-Lord** [comment]
具体实现是这个
https://github.com/Icalingua-plus-plus/oicq-icalingua-plus-plus/blob/master/lib/common.js#L141
seq的话我不确定怎么搞出来，别的都显而易见

**Comment by shenjackyuanjie** [comment]
哇！
谢谢！（才知道是本地生成的，我反正只看到本体那块就没往后看了

**Comment by Young-Lord** [comment]
> 具体实现是这个 https://github.com/Icalingua-plus-plus/oicq-icalingua-plus-plus/blob/master/lib/common.js#L141 seq和pktnum我不确定怎么搞出来，别的都显而易见 或许你可以试试解析Info字段？

可以参考这个
https://www.52pojie.cn/thread-1370802-1-1.html

**Comment by shenjackyuanjie** [comment]
ok, 感谢！

**Comment by shenjackyuanjie** [comment]
后面也许可以改进一下我用来解码的那个东西
