### ISSUE TITLE
可以解析手机备份到电脑的聊天数据库吗

### ISSUE THREAD

**Issue by SakuraXIII** [QQBackup/qq-win-db-key#21]
新版QQ备份到电脑上的聊天记录似乎可以直接打开查看：`...\Tencent Files\<qq>\nt_qq\nt_data\msgbackup\temp\qq.db`，但是关于消息内容的加密方式未知。

**Comment by Young-Lord** [comment]
目前不可。
这个repo貌似是有个获取备份key的脚本的，具体解密方式还不清楚。
