### ISSUE TITLE
[请教] 9.9.7_21453 使用密钥解密无效

### ISSUE THREAD

**Issue by msojocs** [QQBackup/qq-win-db-key#23]
## 版本

WIN_NQ_9.9.7_21453

## 步骤

1. 编写脚本，拿到了数据
    ![image](https://github.com/QQBackup/qq-win-db-key/assets/20937135/d61cc1f3-0bd1-4c17-b171-e8e0be7aeae9)
    ![image](https://github.com/QQBackup/qq-win-db-key/assets/20937135/5b96c61e-eae0-4160-b2e7-90aa85d8879f)
2. 没有关闭QQ，直接复制数据库 `nt_msg.db` 到 `tmp` 文件夹（修改时间是同一分钟）
3. 处理得到 `nt_msg.clean.db`
    ![image](https://github.com/QQBackup/qq-win-db-key/assets/20937135/6d29945b-f70d-43f3-b99c-9bea1dedb721)
4. 复制得到的长度为16的字符串
5. 打开DB Browser for SQLite，粘贴字符串，修改KDF为4000
    ![image](https://github.com/QQBackup/qq-win-db-key/assets/20937135/429ac938-0d67-4c1e-b300-d9f20b50e048)
6. 点击OK

第6步后又出现密码输入框。。。

不知道哪个步骤出现问题？

**Comment by msojocs** [comment]
解决了，使用如下配置：

我在ida看到了HMAC_SHA1的身影：

![image](https://github.com/QQBackup/qq-win-db-key/assets/20937135/03dca3a6-a9bb-4382-a993-9f4cdada949e)

![image](https://github.com/QQBackup/qq-win-db-key/assets/20937135/5b97722e-abd1-4d3e-baae-546f63980996)

![image](https://github.com/QQBackup/qq-win-db-key/assets/20937135/8d49ff8b-0251-4b01-861e-5aa0782ecc0f)

**Comment by Young-Lord** [comment]
好！丢个pr（指在原文旁边加个注释用sha1，或者用脚本找到设定参数的地方）或者我来？方便的话可以把完整脚本也发上来，顺便解决 #22

**Comment by msojocs** [comment]
> 好！丢个pr（指在原文旁边加个注释用sha1，或者用脚本找到设定参数的地方）或者我来？方便的话可以把完整脚本也发上来，顺便解决 #22

你弄吧。

关于[“略加修改”](https://github.com/QQBackup/qq-win-db-key/issues/22#top)：

我这脚本是自己项目改过来的，不是用的本仓库的。https://github.com/msojocs/nt-hook
