### ISSUE TITLE
hook出的key带有问号

### ISSUE THREAD

**Issue by shenapex** [QQBackup/qq-win-db-key#26]
![Screenshot_2024-05-26-13-16-39-167_com termux](https://github.com/QQBackup/qq-win-db-key/assets/110095470/b4f6d83c-70bf-492c-9a0f-c27a63f93d54)
正如图片正如图片那样我所得到的key
Pattern: fd 7b bd a9 f6 57 01 a9 f4 4f 02 a9 fd 03 00 91 f6 03 01 aa f5 03 00 aa ?? ?? ?? ?? f3 03 03 2a f4 03 02 aa
Attach key_v2_function addr: 0x78b8f6fb4c
Frida script injected.
带有问号，请问他是正常的吗。

**Comment by Young-Lord** [comment]
这不是key，这个是调试信息，key前面一般是有个类似`pKey`一样的东西的。
你图里现在还没有获取到key，你可以试着重新登录再看看

**Comment by shenapex** [comment]
![IMG_20240526_163906](https://github.com/QQBackup/qq-win-db-key/assets/110095470/3ed2ecfd-b268-49c7-862e-0a4ba4694325)
十分感谢，我在运行后重新登录了一下获取到了key😘😘
