### ISSUE TITLE
关于Uin获取更快的方法

### ISSUE THREAD

**Issue by molanp** [QQBackup/qq-win-db-key#32]
因为在`/data/user/0/com.tencent.mobileqq/databases/beacon_db_com.tencent.mobileqq`中未找到uid，所以尝试了另一种方法

## 步骤

0. 依次找到`侧边栏-设置-QAuxiliary-[辅助功能]聊天和消息-[消息]转发消息点头像查看详细信息`，开启该功能
1. 向任意联系人发送任意消息(也可以是之前发送的消息，只要是**自己发的消息**就行)
2. 长按该消息-多选-合并转发
3. 转发给任意联系人或群组(建议发给我的电脑)
4. 打开该转发消息，点自己的的头像
5. 点击`详情`
6. 你会看到如下内容(已格式化)
```
MsgRecord{
  msgId=739329401601xxxx,
  msgRandom=49205xxxx,
  msgSeq=19xx,
  cntSeq=0,
  chatType=1,
  msgType=11,
  subMsgType=7,
  sendType=2,
  senderUid=u_xxxx,
  peerUid=xxxx,
  channelId=,
  guildId=,
  guildCode=0,
  fromUid=0,
  fromAppid=0,
  msgTime=1721206556,
  msgMeta=[
  B@a00ceba,
  sendStatus=2,
  ...(省略)
  "prompt":"[聊天记录]",
  "ver":"0.0.0.5",
  "view":"contact"
}
```
7. 其中`senderUid`即为你的uid

**Comment by Young-Lord** [comment]
丢个pr？
其实方法本来就很多，比如网页端登录看Cookies也可以，文档给的只是其中一种方法

**Comment by Young-Lord** [comment]
我更新了个方案，你看看能不能用？

**Comment by molanp** [comment]
> 其实方法本来就很多，比如网页端登录看Cookies也可以，文档给的只是其中一种方法。 而且鉴于这个内容归在“无root”方案里面，我个人觉得需要Xposed的方案还是不太合适…或许还是找一个别的方案更合适些？

可以用npatch onpatch之类的，免root打个本地包就行

**Comment by molanp** [comment]
`/data/user/0/com.tencent.mobileqq/databases/beacon_db_com.tencent.mobileqq`内容大概是个sqlite，搜字符串也搜不到uid，这一步是我的方法不对吗

**Comment by Young-Lord** [comment]
> `/data/user/0/com.tencent.mobileqq/databases/beacon_db_com.tencent.mobileqq`内容大概是个sqlite，搜字符串也搜不到uid，这一步是我的方法不对吗

直接当纯文本打开就行，搜不到我也不确定怎么回事
总而言之现在更新了一个应该更稳定的方法
