### ISSUE TITLE
大佬能否教一下如何获取PCNTQQ的Sessionkey

### ISSUE THREAD

**Issue by xiaomo489** [QQBackup/qq-win-db-key#33]
大佬能否教一下如何获取PCNTQQ的Sessionkey

**Comment by Young-Lord** [comment]
我想这个与本项目（数据库处理）无关吧。

**Comment by Young-Lord** [comment]
@xiaomo489 顺带一提，问别人问题不给报酬，却[靠着修复开源项目bug要钱](https://github.com/TDK1969/nonebot_plugin_bilibilibot/issues/58#issuecomment-1938620090)可不是好行为哦。
