### ISSUE TITLE
pcqq dump 新版本测试可用

### ISSUE THREAD

**Issue by shenjackyuanjie** [QQBackup/qq-win-db-key#35]
我懒得发PR了（
麻烦更新一下可用列表吧

![image](https://github.com/user-attachments/assets/d0f13d7c-1732-45a7-a9a0-b14d099a7455)

9.7.23(29368) 测试可用

**Comment by shenjackyuanjie** [comment]
@QQBackup

**Comment by Young-Lord** [comment]
这个其实可以不用特别更新的……毕竟只是个示例，并非详尽清单
