### ISSUE TITLE
按照NTQQ (Android).md中的方法提取，无法解密数据库文件

### ISSUE THREAD

**Issue by NicoOrz** [QQBackup/qq-win-db-key#36]
Android QQ版本`v9.0.65.17370`
使用方法二，成功得到一串32位的pKey
![d68740a11614da1d602c85c12f50ac1d](https://github.com/user-attachments/assets/19fb99af-e4cd-42a3-92dc-71eff3875e7c)
并且将nt_msg.db提取到电脑上，用下图命令去除纯文本头
![image](https://github.com/user-attachments/assets/ba61933d-ab1c-4bcb-9a71-a197a3442f84)
从纯文本头中看出，使用的HMAC加密是SHA1
![image](https://github.com/user-attachments/assets/a382190d-1c9c-4205-bb2d-1991e340fbbb)
填入密钥对`nt_msg.clean.db`数据库文件解密，失败。
![image](https://github.com/user-attachments/assets/03015b06-abc4-458e-aea8-3a51f893d1ea)

使用方法三，执行后自动跳转qq，几秒后跳转回终端页面，但/sdcard/0/Downloads文件夹中没有看见生成的数据库文件
![3fab71f80e7cea571e33148c98c5f6a6](https://github.com/user-attachments/assets/799f3e7f-3ea6-4beb-977f-8ee28d73072d)
求各位大佬支招！！（滑跪

**Comment by Young-Lord** [comment]
尝试[方法1](https://github.com/QQBackup/qq-win-db-key/blob/master/%E6%95%99%E7%A8%8B%20-%20NTQQ%20(Android).md#%E6%96%B9%E6%B3%951%E6%8E%A8%E8%8D%90)？

**Comment by Young-Lord** [comment]
没有回复，先close了
