### ISSUE TITLE
Mac QQ聊天记录、文件和缓存客户端全部清除后QQ.db和nt_db文件夹仍有很多残留文件

### ISSUE THREAD

**Issue by HaiBingmo** [QQBackup/qq-win-db-key#39]
最新版QQ在客户端存储管理全部点击清除选项后，发现/Users/【用户名】/Library/Containers/QQ的文件夹大小比客户端显示空间佔用还要大不少，里面各种地方还有很多图片和一些语音聊天记录（清除前后在客户端翻历史记录翻不出这些内容，似乎是已经被QQ遗弃了）。然后发现com.tencent.qq/Data/Documents/contents/【QQ号】/QQ.db仍有几十MB（另一个登录过的没怎么用过的QQ号此处就没有什么大小），nt_msg.db和group_msg_fts.db等总共仍有几百MB大小，它们的最近修改日期都在近日。请问这些是残存的聊天记录吗，这两处文件有什么区别？

**Comment by Young-Lord** [comment]
1. 与这个项目无关
2. 貌似这个团队的成员没有几个有 macOS 环境 或 知识 的，不好调试

综上，我建议你去 v2ex 一类的地方问，收到回复的可能性更大。
