### ISSUE TITLE
解密PCQQ聊天数据库firda提示权限不足

### ISSUE THREAD

**Issue by shaozi127** [QQBackup/qq-win-db-key#41]
注：本人已经干掉了qqprotect，firda版本为16.5.2，python版本311，系统为windows10 22H2
参考了项目https://github.com/QQBackup/qq-win-db-key/blob/master/%E6%95%99%E7%A8%8B%20-%20PCQQ%20(Windows).md
无论是使用pcqq_dump.py还是pcqq_get_key.py均提示权限不足
以下是详细报错信息

`C:\Users\Administrator\Desktop>python pcqq_dump.py
QQ pid is: 6416
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\pcqq_dump.py", line 178, in <module>
    session = frida.get_local_device().attach(QQ_PID)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\frida\core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\frida\core.py", line 1071, in attach
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.NotSupportedError: unexpectedly failed with error code: 0x00000057`
本人在[issues35](https://github.com/QQBackup/qq-win-db-key/issues/35)发现这个版本可以于是回退到了更早的29345发现依旧不行
我也尝试过了各种提权不管是给管理员还是什么可是就是附加不上去😭
![QQ截图20241002203958](https://github.com/user-attachments/assets/bb208cc4-b952-4673-b42c-d7679aee0424)

**Comment by Burgerd4sh** [comment]
我刚刚试过了，使用frida 16.4.10版本的可行。16.5的版本因为windows系统特性的原因不好使。

**Comment by shaozi127** [comment]
> 我刚刚试过了，使用frida 16.4.10版本的可行。16.5的版本因为windows系统特性的原因不好使。

感谢大佬，我是用16.4.10版本的firda成功hook到了❤

**Comment by Burgerd4sh** [comment]
记得close一下issue

**Comment by Young-Lord** [comment]
上游issue: https://github.com/frida/frida/issues/2964
我去文档加行字吧
