### ISSUE TITLE
我想将我的聊天记录归档并进行后续处理,请问目前最好的方法是什么?

### ISSUE THREAD

**Issue by TeamBreakerr** [QQBackup/qq-win-db-key#45]
我的聊天记录分散到各个端都不完整.
看了这个项目,请问我是否可以使用客户端自带的导出导入功能将聊天记录合并到一个端,再使用该项目进行解密?
请问目前推荐在哪一个客户端进行操作呢?
最终会得到一个被解密的SQLite数据库吗?
后续想用来训练LLM,并使用qq机器人进行实时的消息记录保存.

**Comment by Young-Lord** [comment]
> 是否可以使用客户端自带的导出导入功能将聊天记录合并到一个端,再使用该项目进行解密?

理论可行，实际未尝试。

> 请问目前推荐在哪一个客户端进行操作呢?

在Android端可以使用[这个方法](https://github.com/QQBackup/qq-win-db-key/blob/master/%E6%95%99%E7%A8%8B%20-%20NTQQ%20(Android).md#%E6%96%B9%E6%B3%951%E6%8E%A8%E8%8D%90)，在不对QQ进程本身进行修改的情况下揭秘数据库，理论上最安全。其他平台可能也可以使用相同方法，但是未验证。

> 最终会得到一个被解密的SQLite数据库吗?

是。
